---
- name: ensure mysql upstream repository package is downloaded
  get_url:
    url: http://dev.mysql.com/get/mysql-apt-config_0.8.6-1_all.deb
    dest: /root/mysql-apt-config.deb

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keys.gnupg.net
    id: 8C718D3B5072E1F5

- name: ensure mysql upstream repository package is configured
  debconf:
    name: mysql-apt-config
    question: "mysql-apt-config/{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype | default ('select') }}"
  with_items:
    - question: repo-distro
      value: "{{ ansible_distribution | lower }}"
    - question: repo-codename
      value: "{{ ansible_distribution_release }}"
    - question: select-server
      value: "mysql-{{ mysql_upstream_version }}"

#- lineinfile:
#    path: /etc/apt/apt.conf.d/99mysql
#    line: 'APT::Get::AllowUnauthenticated "true";'
#    create: yes
    
- name: ensure mysql upstream repository is installed
  apt:
    deb: /root/mysql-apt-config.deb
  register: mysql_upstream_repository_installation

- name: ensure apt cache is updated
  apt:
    update_cache: yes
  changed_when: false
  when: mysql_upstream_repository_installation is changed
